package com.serpics.admin.ui;

import javax.annotation.Resource;

import org.springframework.beans.factory.InitializingBean;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.serpics.catalog.persistence.Category;
import com.serpics.catalog.services.CatalogService;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Tree;
import com.vaadin.ui.VerticalLayout;

@Component
@Scope("prototype")
public class CatTree extends CustomComponent implements InitializingBean {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalSplitPanel horizontalSplitPanel_1;
	@AutoGenerated
	private Tree catTree;
	
	
	
	@Resource
	CatalogService catalogService;
	
	
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public CatTree() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
	
	}

	
	@Override
	public void afterPropertiesSet() throws Exception {
		Category c = new Category();
		c.setCode("AAA");
		c.setUrl("/AAA");
		
		catalogService.createCategory(c, null);
		
		Category b = new Category();
		b.setCode("BBB");
		b.setUrl("/BBB");
		
		catalogService.createCategory(b, c);
//		
//		for (Category ca : catalogService.findRootCategory()){
//			System.out.println(ca.getCode());
//		}
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalSplitPanel_1
		horizontalSplitPanel_1 = buildHorizontalSplitPanel_1();
		mainLayout.addComponent(horizontalSplitPanel_1);
		mainLayout.setExpandRatio(horizontalSplitPanel_1, 1.0f);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildHorizontalSplitPanel_1() {
		// common part: create layout
		horizontalSplitPanel_1 = new HorizontalSplitPanel();
		horizontalSplitPanel_1.setImmediate(false);
		horizontalSplitPanel_1.setWidth("200px");
		horizontalSplitPanel_1.setHeight("100.0%");
		
		// catTree
		catTree = new Tree();
		catTree.setImmediate(false);
		catTree.setWidth("-1px");
		catTree.setHeight("100.0%");
		horizontalSplitPanel_1.addComponent(catTree);
		
		return horizontalSplitPanel_1;
	}




}
