
DROP TABLE CTENTRY_ATTRIBUTE_VALUE_DECIMAL;
DROP TABLE CTENTRY_ATTRIBUTE_VALUE_LONG;
DROP TABLE CTENTRY_ATTRIBUTE_VALUE_TEXT;
DROP TABLE CTENTRY_ATTRIBUTE_VALUE_VARCHAR;
DROP TABLE CTENTRY_ATTRIBUTE_VALUE_DATETIME;
DROP TABLE CTENTRY_ATTRIBUTES;

DROP TABLE MEMBER_ATTRIBUTE_VALUE_DATETIME;
DROP TABLE MEMBER_ATTRIBUTE_VALUE_DECIMAL;
DROP TABLE MEMBER_ATTRIBUTE_VALUE_LONG;
DROP TABLE MEMBER_ATTRIBUTE_VALUE_TEXT;
DROP TABLE MEMBER_ATTRIBUTE_VALUE_VARCHAR;
DROP TABLE MEMBER_ATTRIBUTE;
DROP TABLE ORDERITEMS_ATTRIBUTE_VALUE_DATETIME;
DROP TABLE ORDERITEMS_ATTRIBUTE_VALUE_DECIMAL;
DROP TABLE ORDERITEMS_ATTRIBUTE_VALUE_LONG;
DROP TABLE ORDERITEMS_ATTRIBUTE_VALUE_TEXT;
DROP TABLE ORDERITEMS_ATTRIBUTE_VALUE_VARCHAR;
DROP TABLE ORDERITEMS_ATTRIBUTE;
DROP TABLE ORDERS_ATTRIBUTE_VALUE_DATETIME;
DROP TABLE ORDERS_ATTRIBUTE_VALUE_DECIMAL;
DROP TABLE ORDERS_ATTRIBUTE_VALUE_LONG;
DROP TABLE ORDERS_ATTRIBUTE_VALUE_TEXT;
DROP TABLE ORDERS_ATTRIBUTE_VALUE_VARCHAR;
DROP TABLE ORDERS_ATTRIBUTE;

DROP TABLE ATTRIBUTE_LOOKUP;
DROP TABLE BASE_ATTRIBUTES;
